# Generated by Django 5.2.10 on 2026-02-16 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_profile_address_alter_profile_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="role",
            field=models.CharField(
                choices=[
                    ("Admin", "Admin"),
                    ("Vendor", "Vendor"),
                    ("Customer", "Customer"),
                ],
                default="Customer",
                max_length=10,
            ),
        ),
    ]
