# Generated by Django 5.2.10 on 2026-02-17 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_product_vendor_alter_category_slug_and_more"),
        ("users", "0004_profile_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="wishlist",
            field=models.ManyToManyField(
                blank=True, related_name="wishlisted_by", to="products.product"
            ),
        ),
    ]
